try{
    throw new Error(a);
}

catch(b)
{
    b++;
}
finally
{
    
}
